Build ingress-nginx controller version 0.27.1 with FIPS support
infobloxopen/ingress-nginx pull request #4
Opened 2020-10-08 15:48 UTC by alavrovinfb

- re-built NGINX with FIPS support
- re-built ingress-nginx controller with FIPS support

2020-10-08 17:06 UTC, Evgeniy-L approved these changes
Looks ok to me

2020-10-08 17:20 UTC, kd7lxl reviewed
Do you have any suggestions on how this can be validated? Is there some build/test we should run with CI?

2020-10-08 18:02 UTC, daniel-garcia requested changes
The end of this (building) should be able to verify that openssl doesn't have md5 support and nginx lacks at least one crypto type that should have been removed.

2020-10-08 18:02 UTC, daniel-garcia commented on images/nginx/rootfs/build.sh
> +adduser -u 101 -M -d /usr/local/nginx \
are the userland tools different? is that why the args are different? if so, please comment upstream commands and write the updated commands separately

2020-10-08 18:11 UTC, alavrovinfb commented
> Do you have any suggestions on how this can be validated? Is there some build/test we should run with CI?

This image has been built based on Amazon Linux 2 that is conforms to FIPS and validated by NIST.
To test FIPS within CI the image must be deployed on the host system that configured with FIPS mode or we need to force FIPS mode enabling. Any way we can perform only some simple tests.

2020-10-08 18:16 UTC, alavrovinfb commented on Makefile
> +TAG ?= v0.27.1
> eg circleci or jenkins
Do we use circleci or jenkins for infobloxopen repos? I think we use travis-ci for it.

2020-10-08 18:43 UTC, kd7lxl commented on Makefile
> +TAG ?= v0.27.1
In other infobloxopen repos, we have used Jenkins, Github Actions, and travis-ci.

2020-10-08 18:54 UTC, alavrovinfb commented on Makefile
> +TAG ?= v0.27.1
I see at least one project uses circle-ci https://app.circleci.com/pipelines/github/infobloxopen/seal

2020-10-08 19:07 UTC, kd7lxl commented on Makefile
> +TAG ?= v0.27.1
Sounds like there's no significant limitation on what build driver you can use for this.

2020-10-14 13:09 UTC, alavrovinfb commented
Added simple OpenSSL fips mode test.
Some manual testing was done on FIPS enabled EC2 instance.
![Uploading Screenshot at 2020-10-14 12-47-37.png…]()

2020-10-14 17:34 UTC, daniel-garcia approved these changes

2020-10-14 17:44 UTC, merged